### ISSUE TITLE
Cannot upload file

### ISSUE THREAD

**Issue by scadox** [trippo/ResponsiveFilemanager#422]
Hi ResponsiveFilemanager team,

i try use new version 9.12.1 from lastest download available and i have always error when try upload file(s). I have paste this below the output try catch error PHP.

Always multiple undefined index from UploadHandler.php with method ( get_server_var or get_query_param ).

Thank ou for help.

#1 C:\wamp64\www\intellij\globocms\backend\modulePHP\fileManager\9.12.1\UploadHandler.php(1323): UploadHandler->get_query_param('_method')
#2 C:\wamp64\www\intellij\globocms\backend\modulePHP\fileManager\9.12.1\UploadHandler.php(187): UploadHandler->post(false)
#3 C:\wamp64\www\intellij\globocms\backend\modulePHP\fileManager\9.12.1\UploadHandler.php(171): UploadHandler->initialize()
#4 C:\wamp64\www\intellij\globocms\backend\modulePHP\fileManager\9.12.1\upload.php(142): UploadHandler->__construct(Array, true, Array)
#5 Undefined index: HTTP_CONTENT_DISPOSITION Ligne 1158

#1 C:\wamp64\www\intellij\globocms\backend\modulePHP\fileManager\9.12.1\UploadHandler.php(1328): UploadHandler->get_server_var('HTTP_CONTENT_DI...')
#2 C:\wamp64\www\intellij\globocms\backend\modulePHP\fileManager\9.12.1\UploadHandler.php(187): UploadHandler->post(false)
#3 C:\wamp64\www\intellij\globocms\backend\modulePHP\fileManager\9.12.1\UploadHandler.php(171): UploadHandler->initialize()
#4 C:\wamp64\www\intellij\globocms\backend\modulePHP\fileManager\9.12.1\upload.php(142): UploadHandler->__construct(Array, true, Array)
#5 Undefined index: HTTP_CONTENT_RANGE Ligne 1158

#1 C:\wamp64\www\intellij\globocms\backend\modulePHP\fileManager\9.12.1\UploadHandler.php(1337): UploadHandler->get_server_var('HTTP_CONTENT_RA...')
#2 C:\wamp64\www\intellij\globocms\backend\modulePHP\fileManager\9.12.1\UploadHandler.php(187): UploadHandler->post(false)
#3 C:\wamp64\www\intellij\globocms\backend\modulePHP\fileManager\9.12.1\UploadHandler.php(171): UploadHandler->initialize()
#4 C:\wamp64\www\intellij\globocms\backend\modulePHP\fileManager\9.12.1\upload.php(142): UploadHandler->__construct(Array, true, Array)
#5 Undefined index: Orientation Ligne 421

#1 C:\wamp64\www\intellij\globocms\backend\modulePHP\fileManager\9.12.1\UploadHandler.php(1067): UploadHandler->validate('C:\\wamp64\\tmp\\p...', Object(stdClass), 0, 0)
#2 C:\wamp64\www\intellij\globocms\backend\modulePHP\fileManager\9.12.1\UploadHandler.php(1355): UploadHandler->handle_file_upload('C:\\wamp64\\tmp\\p...', 'MondoIn_roomSrv...', 132183, 'image/jpeg', 0, 0, NULL)
#3 C:\wamp64\www\intellij\globocms\backend\modulePHP\fileManager\9.12.1\UploadHandler.php(187): UploadHandler->post(false)
#4 C:\wamp64\www\intellij\globocms\backend\modulePHP\fileManager\9.12.1\UploadHandler.php(171): UploadHandler->initialize()
#5 C:\wamp64\www\intellij\globocms\backend\modulePHP\fileManager\9.12.1\upload.php(142): UploadHandler->__construct(Array, true, Array)
#6 Undefined index: Orientation Ligne 628

{"files":[{"name":"MondoIn_roomSrv03.jpg","size":132183,"type":"image\/jpeg","path":"C:\/wamp64\/www\/intellij\/globocms\/backend\/modulePHP\/fileManager\/9.12.1\/..\/..\/..\/..\/assets\/source\/base\/MondoIn_roomSrv03.jpg","url":"\/intellij\/globocms\/assets\/source\/base\/MondoIn_roomSrv03.jpg","deleteUrl":"http:\/\/localhost\/intellij\/globocms\/backend\/modulePHP\/fileManager\/9.12.1\/upload.php?file=MondoIn_roomSrv03.jpg","deleteType":"DELETE"}]}

**Comment by podolinek** [comment]
Chrome: Upload file on demo doesn't work in demo either.
