### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by khadkasimon** [trippo/ResponsiveFilemanager#602]
SyntaxError: Unexpected token < in JSON at position 0 While Uploading Image php 7.4.0
![image](https://user-images.githubusercontent.com/10781554/77741779-8ed71e00-703d-11ea-991e-15bf10ba7a3c.png)

**Comment by trippo** [comment]
You must check the error on the network tab of inspector

**Comment by labby** [comment]
please see image, error 
![bug_json](https://user-images.githubusercontent.com/1763282/77916923-233dbc80-729a-11ea-8f61-230593360285.jpg)
appears with php 7.4.4
with php 7.2x it is working well (same file, same procedure)

**Comment by labby** [comment]
using drag and drop it throws
Fatal error: Uncaught Error: Call to undefined function mime_content_type() in F:\_LEPTON\LEPTON_mobile\root\4x\upload\modules\lib_r_filemanager\filemanager\include\php_image_magician.php:2723 Stack trace: #0 F:\_LEPTON\LEPTON_mobile\root\4x\upload\modules\lib_r_filemanager\filemanager\include\php_image_magician.php(230): imageLib->openImage('../../..//media...') #1 F:\_LEPTON\LEPTON_mobile\root\4x\upload\modules\lib_r_filemanager\filemanager\include\utils.php(425): imageLib->__construct('../../..//media...') #2 F:\_LEPTON\LEPTON_mobile\root\4x\upload\modules\lib_r_filemanager\filemanager\dialog.php(1116): create_img('../../..//media...', '../thumbs/produ...', 122, 91, 'crop', Array) #3 {main} thrown in F:\_LEPTON\LEPTON_mobile\root\4x\upload\modules\lib_r_filemanager\filemanager\include\php_image_magician.php on line 2723

**Comment by topapay** [comment]
SyntaxError: Unexpected token < in JSON at position 0 While Uploading Image php 7.4.5 , use FTP, error on the network tab of inspector 

<br />
<b>Warning</b>:  move_uploaded_file(../temp/1hYOVXH.jpg): failed to open stream: Permission denied in <b>/var/www/html/kelola/assets/tinymce/filemanager/UploadHandler.php</b> on line <b>1168</b><br />
<br />
<b>Warning</b>:  move_uploaded_file(): Unable to move '/tmp/phpnqJiWh' to '../temp/1hYOVXH.jpg' in <b>/var/www/html/kelola/assets/tinymce/filemanager/UploadHandler.php</b> on line <b>1168</b><br />
<br />
<b>Warning</b>:  filesize(): stat failed for ../temp/1hYOVXH.jpg in <b>/var/www/html/kelola/assets/tinymce/filemanager/UploadHandler.php</b> on line <b>322</b><br />
<br />
<b>Warning</b>:  unlink(../temp/1hYOVXH.jpg): No such file or directory in <b>/var/www/html/kelola/assets/tinymce/filemanager/UploadHandler.php</b> on line <b>1187</b><br />
{"files":[{"name":"1hYOVXH.jpg","size":false,"type":"image\/jpeg","error":"File upload aborted","deleteUrl":"https:\/\/rsud.brebeskab.go.id\/kelola\/assets\/tinymce\/filemanager\/upload.php?file=1hYOVXH.jpg","deleteType":"DELETE"}]}
